import builtins from "builtin-modules";
import dotenv from "dotenv";
import esbuild from "esbuild";
import * as fs from "fs";
import * as path from "path";
import process from "process";

dotenv.config();

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;
const exportToVault = (process.argv[3] === "export");
const prod = (process.argv[2] === "production");

const moveStyles = {
	name: "move-styles",
	setup(build) {
		build.onEnd(() => {
			if (fs.existsSync("plugin/styles.css")) fs.copyFileSync("plugin/styles.css", "./styles.css");
		});
	}
};

const exportToVaultFunc = {
	name: "export-to-vault",
	setup(build) {
		build.onEnd(() => {
			if (!(prod && exportToVault)) {
				return;
			}
			if (!process.env.VAULT_PATH) {
				console.error("VAULT_PATH environment variable not set, skipping export to vault");
				return;
			}
			const vaultPath = process.env.VAULT_PATH;
			const pluginManifest = JSON.parse(fs.readFileSync("./manifest.json", "utf-8"));
			const pluginId = pluginManifest.id;
			const pluginFolder = path.join(vaultPath,".obsidian", "plugins", pluginId);
			if (!fs.existsSync(pluginFolder)) {
				fs.mkdirSync(pluginFolder, {recursive: true});
			}
			fs.copyFileSync("./main.js", path.join(pluginFolder, "main.js"));
			if (fs.existsSync("./styles.css")) fs.copyFileSync("./styles.css", path.join(pluginFolder, "styles.css"));
			fs.copyFileSync("./manifest.json", path.join(pluginFolder, "manifest.json"));
		});
	}
};

const exportToDist = {
	name: "export-to-dist",
	setup(build) {
		build.onEnd(() => {
			if (!prod) {
				return;
			}
			if (!fs.existsSync("./dist")) {
				fs.mkdirSync("./dist");
			}
			fs.copyFileSync("main.js", path.join("./dist", "main.js"));
			if (fs.existsSync("styles.css"))
				fs.copyFileSync("styles.css", path.join("./dist", "styles.css"));
			fs.copyFileSync("manifest.json", path.join("./dist", "manifest.json"));
		});
	}
};

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ["plugin/main.ts", "plugin/styles.css"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	watch: !prod,
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod,
	treeShaking: true,
	outdir: "./",
	plugins: [moveStyles, exportToDist, exportToVaultFunc],
}).catch(() => process.exit(1));